<template>
  <div class="about">
    
    <h1>About page</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio numquam perspiciatis excepturi aliquid provident repellat eligendi minus deserunt temporibus? Totam deserunt, eveniet tempore temporibus cum velit? Perspiciatis pariatur aspernatur cumque assumenda esse, similique fugiat dolores, mollitia voluptate, odit cupiditate repellendus! Eligendi distinctio perspiciatis illo eaque quod, at necessitatibus, numquam atque nulla, minus excepturi? Odio tempore ullam, aperiam voluptate dicta impedit incidunt ipsa dolorum facilis ut corporis ab. Quasi recusandae quae voluptas obcaecati perspiciatis itaque saepe aut? Quis, sequi quos nam dolores nemo ex officia aliquid quod mollitia fuga assumenda quisquam sed ab, perferendis minus praesentium tempore quasi saepe unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio numquam perspiciatis excepturi aliquid provident repellat eligendi minus deserunt temporibus? Totam deserunt, eveniet tempore temporibus cum velit? Perspiciatis pariatur aspernatur cumque assumenda esse, similique fugiat dolores, mollitia voluptate, odit cupiditate repellendus! Eligendi distinctio perspiciatis illo eaque quod, at necessitatibus, numquam atque nulla, minus excepturi? Odio tempore ullam, aperiam voluptate dicta impedit incidunt ipsa dolorum facilis ut corporis ab. Quasi recusandae quae voluptas obcaecati perspiciatis itaque saepe aut? Quis, sequi quos nam dolores nemo ex officia aliquid quod mollitia fuga assumenda quisquam sed ab, perferendis minus praesentium tempore quasi saepe unde?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus distinctio numquam perspiciatis excepturi aliquid provident repellat eligendi minus deserunt temporibus? Totam deserunt, eveniet tempore temporibus cum velit? Perspiciatis pariatur aspernatur cumque assumenda esse, similique fugiat dolores, mollitia voluptate, odit cupiditate repellendus! Eligendi distinctio perspiciatis illo eaque quod, at necessitatibus, numquam atque nulla, minus excepturi? Odio tempore ullam, aperiam voluptate dicta impedit incidunt ipsa dolorum facilis ut corporis ab. Quasi recusandae quae voluptas obcaecati perspiciatis itaque saepe aut? Quis, sequi quos nam dolores nemo ex officia aliquid quod mollitia fuga assumenda quisquam sed ab, perferendis minus praesentium tempore quasi saepe unde?</p>
  </div>
</template>
